import { Category } from "./types";

export const SESSION_STORAGE_KEYS = {
  SESSION_ID: "ta_session_id",
  VIEWED_PREFIX: "ta_viewed_",
} as const;

export const CATEGORIES = [
  "Artificial Intelligence",
  "Marketing",
  "E-commerce",
  "Design Tools",
  "Developer Tools",
  "Fintech",
  "Productivity",
  "No-Code",
  "Analytics",
  "SaaS",
  "Hosting & Web",
  "Utilities",
  "Education",
] as const;

export const CATEGORY_ICONS: Readonly<Record<Category, string>> = {
  "Artificial Intelligence": "HiSparkles",
  Marketing: "HiMegaphone",
  "E-commerce": "HiShoppingCart",
  "Design Tools": "HiPaintBrush",
  "Developer Tools": "HiWrenchScrewdriver",
  Fintech: "HiCreditCard",
  Productivity: "HiBolt",
  "No-Code": "HiPuzzlePiece",
  Analytics: "HiChartBar",
  SaaS: "HiCloud",
  "Hosting & Web": "HiServerStack",
  Utilities: "HiWrench",
  Education: "HiAcademicCap",
} as const;

export const CATEGORY_SLUGS: Readonly<Record<Category, string>> = {
  "Artificial Intelligence": "ai",
  Marketing: "marketing",
  "E-commerce": "ecommerce",
  "Design Tools": "design-tools",
  "Developer Tools": "developer-tools",
  Fintech: "fintech",
  Productivity: "productivity",
  "No-Code": "no-code",
  Analytics: "analytics",
  SaaS: "saas",
  "Hosting & Web": "hosting-web",
  Utilities: "utilities",
  Education: "education",
} as const;

export const getSlugFromCategory = (category: Category): string =>
  CATEGORY_SLUGS[category] || category.toLowerCase().replace(/\s+/g, "-");

export const getCategoryFromSlug = (slug: string): Category | null => {
  const entry = Object.entries(CATEGORY_SLUGS).find(([_, s]) => s === slug);
  return entry ? (entry[0] as Category) : null;
};

export const VALID_COUNTRIES = [
  "US", "GB", "DE", "FR", "ES", "IT", "NL", "BE", "AT", "CH", "SE", "NO", "DK", "FI", "IE", "PT", "PL", "CZ", "HU", "RO", "GR", "SK", "BG", "HR", "LT", "LV", "EE", "SI", "LU", "IS", "MT", "CY", "RU", "UA", "BY", "MD", "AL", "BA", "ME", "MK", "RS", "AM", "AZ", "GE", "TR", "CA", "MX", "BR", "AR", "CO", "CL", "PE", "VE", "EC", "BO", "PY", "UY", "CR", "PA", "DO", "GT", "HN", "SV", "NI", "CU", "JM", "TT", "AU", "NZ", "JP", "KR", "CN", "IN", "ID", "TH", "VN", "MY", "PH", "SG", "TW", "HK", "MO", "PK", "BD", "LK", "NP", "KP", "KH", "LA", "MM", "UZ", "KZ", "TM", "TJ", "KG", "AE", "SA", "IL", "TR", "QA", "KW", "OM", "BH", "JO", "LB", "SY", "IQ", "IR", "YE", "PS", "EG", "ZA", "NG", "KE", "MA", "DZ", "TN", "LY", "ET", "GH", "TZ", "UG", "SN", "CI", "CM", "AO", "MZ", "ZM", "ZW", "NA", "BW", "MU", "RW", "SD", "SS", "ML", "BF", "NE", "GN", "LR", "SL", "BJ", "TG", "GA", "CG", "CD", "GQ", "ST", "SC", "MG", "MR", "ER", "DJ", "SO", "LS", "SZ", "MW", "BI", "KM", "Other"
] as const;

export const COUNTRIES = [
  { code: "US", name: "United States", flag: "🇺🇸" },
  { code: "GB", name: "United Kingdom", flag: "🇬🇧" },
  { code: "DE", name: "Germany", flag: "🇩🇪" },
  { code: "FR", name: "France", flag: "🇫🇷" },
  { code: "ES", name: "Spain", flag: "🇪🇸" },
  { code: "IT", name: "Italy", flag: "🇮🇹" },
  { code: "NL", name: "Netherlands", flag: "🇳🇱" },
  { code: "BE", name: "Belgium", flag: "🇧🇪" },
  { code: "AT", name: "Austria", flag: "🇦🇹" },
  { code: "CH", name: "Switzerland", flag: "🇨🇭" },
  { code: "SE", name: "Sweden", flag: "🇸🇪" },
  { code: "NO", name: "Norway", flag: "🇳🇴" },
  { code: "DK", name: "Denmark", flag: "🇩🇰" },
  { code: "FI", name: "Finland", flag: "🇫🇮" },
  { code: "IE", name: "Ireland", flag: "🇮🇪" },
  { code: "PT", name: "Portugal", flag: "🇵🇹" },
  { code: "PL", name: "Poland", flag: "🇵🇱" },
  { code: "CZ", name: "Czech Republic", flag: "🇨🇿" },
  { code: "HU", name: "Hungary", flag: "🇭🇺" },
  { code: "RO", name: "Romania", flag: "🇷🇴" },
  { code: "GR", name: "Greece", flag: "🇬🇷" },
  { code: "SK", name: "Slovakia", flag: "🇸🇰" },
  { code: "BG", name: "Bulgaria", flag: "🇧🇬" },
  { code: "HR", name: "Croatia", flag: "🇭🇷" },
  { code: "LT", name: "Lithuania", flag: "🇱🇹" },
  { code: "LV", name: "Latvia", flag: "🇱🇻" },
  { code: "EE", name: "Estonia", flag: "🇪🇪" },
  { code: "SI", name: "Slovenia", flag: "🇸🇮" },
  { code: "LU", name: "Luxembourg", flag: "🇱🇺" },
  { code: "IS", name: "Iceland", flag: "🇮🇸" },
  { code: "MT", name: "Malta", flag: "🇲🇹" },
  { code: "CY", name: "Cyprus", flag: "🇨🇾" },
  { code: "RU", name: "Russia", flag: "🇷🇺" },
  { code: "UA", name: "Ukraine", flag: "🇺🇦" },
  { code: "BY", name: "Belarus", flag: "🇧🇾" },
  { code: "MD", name: "Moldova", flag: "🇲🇩" },
  { code: "AL", name: "Albania", flag: "🇦🇱" },
  { code: "BA", name: "Bosnia and Herzegovina", flag: "🇧🇦" },
  { code: "ME", name: "Montenegro", flag: "🇲🇪" },
  { code: "MK", name: "North Macedonia", flag: "🇲🇰" },
  { code: "RS", name: "Serbia", flag: "🇷🇸" },
  { code: "AM", name: "Armenia", flag: "🇦🇲" },
  { code: "AZ", name: "Azerbaijan", flag: "🇦🇿" },
  { code: "GE", name: "Georgia", flag: "🇬🇪" },
  { code: "TR", name: "Turkey", flag: "🇹🇷" },
  { code: "CA", name: "Canada", flag: "🇨🇦" },
  { code: "MX", name: "Mexico", flag: "🇲🇽" },
  { code: "BR", name: "Brazil", flag: "🇧🇷" },
  { code: "AR", name: "Argentina", flag: "🇦🇷" },
  { code: "CO", name: "Colombia", flag: "🇨🇴" },
  { code: "CL", name: "Chile", flag: "🇨🇱" },
  { code: "PE", name: "Peru", flag: "🇵🇪" },
  { code: "VE", name: "Venezuela", flag: "🇻🇪" },
  { code: "EC", name: "Ecuador", flag: "🇪🇨" },
  { code: "BO", name: "Bolivia", flag: "🇧🇴" },
  { code: "PY", name: "Paraguay", flag: "🇵🇾" },
  { code: "UY", name: "Uruguay", flag: "🇺🇾" },
  { code: "CR", name: "Costa Rica", flag: "🇨🇷" },
  { code: "PA", name: "Panama", flag: "🇵🇦" },
  { code: "DO", name: "Dominican Republic", flag: "🇩🇴" },
  { code: "GT", name: "Guatemala", flag: "🇬🇹" },
  { code: "HN", name: "Honduras", flag: "🇭🇳" },
  { code: "SV", name: "El Salvador", flag: "🇸🇻" },
  { code: "NI", name: "Nicaragua", flag: "🇳🇮" },
  { code: "CU", name: "Cuba", flag: "🇨🇺" },
  { code: "JM", name: "Jamaica", flag: "🇯🇲" },
  { code: "TT", name: "Trinidad and Tobago", flag: "🇹🇹" },
  { code: "AU", name: "Australia", flag: "🇦🇺" },
  { code: "NZ", name: "New Zealand", flag: "🇳🇿" },
  { code: "JP", name: "Japan", flag: "🇯🇵" },
  { code: "KR", name: "South Korea", flag: "🇰🇷" },
  { code: "CN", name: "China", flag: "🇨🇳" },
  { code: "IN", name: "India", flag: "🇮🇳" },
  { code: "ID", name: "Indonesia", flag: "🇮🇩" },
  { code: "TH", name: "Thailand", flag: "🇹🇭" },
  { code: "VN", name: "Vietnam", flag: "🇻🇳" },
  { code: "MY", name: "Malaysia", flag: "🇲🇾" },
  { code: "PH", name: "Philippines", flag: "🇵🇭" },
  { code: "SG", name: "Singapore", flag: "🇸🇬" },
  { code: "TW", name: "Taiwan", flag: "🇹🇼" },
  { code: "HK", name: "Hong Kong", flag: "🇭🇰" },
  { code: "MO", name: "Macao", flag: "🇲🇴" },
  { code: "PK", name: "Pakistan", flag: "🇵🇰" },
  { code: "BD", name: "Bangladesh", flag: "🇧🇩" },
  { code: "LK", name: "Sri Lanka", flag: "🇱🇰" },
  { code: "NP", name: "Nepal", flag: "🇳🇵" },
  { code: "KP", name: "North Korea", flag: "🇰🇵" },
  { code: "KH", name: "Cambodia", flag: "🇰🇭" },
  { code: "LA", name: "Laos", flag: "🇱🇦" },
  { code: "MM", name: "Myanmar", flag: "🇲🇲" },
  { code: "UZ", name: "Uzbekistan", flag: "🇺🇿" },
  { code: "KZ", name: "Kazakhstan", flag: "🇰🇿" },
  { code: "TM", name: "Turkmenistan", flag: "🇹🇲" },
  { code: "TJ", name: "Tajikistan", flag: "🇹🇯" },
  { code: "KG", name: "Kyrgyzstan", flag: "🇰🇬" },
  { code: "AE", name: "United Arab Emirates", flag: "🇦🇪" },
  { code: "SA", name: "Saudi Arabia", flag: "🇸🇦" },
  { code: "IL", name: "Israel", flag: "🇮🇱" },
  { code: "QA", name: "Qatar", flag: "🇶🇦" },
  { code: "KW", name: "Kuwait", flag: "🇰🇼" },
  { code: "OM", name: "Oman", flag: "🇴🇲" },
  { code: "BH", name: "Bahrain", flag: "🇧🇭" },
  { code: "JO", name: "Jordan", flag: "🇯🇴" },
  { code: "LB", name: "Lebanon", flag: "🇱🇧" },
  { code: "SY", name: "Syria", flag: "🇸🇾" },
  { code: "IQ", name: "Iraq", flag: "🇮🇶" },
  { code: "IR", name: "Iran", flag: "🇮🇷" },
  { code: "YE", name: "Yemen", flag: "🇾🇪" },
  { code: "PS", name: "Palestine", flag: "🇵🇸" },
  { code: "EG", name: "Egypt", flag: "🇪🇬" },
  { code: "ZA", name: "South Africa", flag: "🇿🇦" },
  { code: "NG", name: "Nigeria", flag: "🇳🇬" },
  { code: "KE", name: "Kenya", flag: "🇰🇪" },
  { code: "MA", name: "Morocco", flag: "🇲🇦" },
  { code: "DZ", name: "Algeria", flag: "🇩🇿" },
  { code: "TN", name: "Tunisia", flag: "🇹🇳" },
  { code: "LY", name: "Libya", flag: "🇱🇾" },
  { code: "ET", name: "Ethiopia", flag: "🇪🇹" },
  { code: "GH", name: "Ghana", flag: "🇬🇭" },
  { code: "TZ", name: "Tanzania", flag: "🇹🇿" },
  { code: "UG", name: "Uganda", flag: "🇺🇬" },
  { code: "SN", name: "Senegal", flag: "🇸🇳" },
  { code: "CI", name: "Ivory Coast", flag: "🇨🇮" },
  { code: "CM", name: "Cameroon", flag: "🇨🇲" },
  { code: "AO", name: "Angola", flag: "🇦🇴" },
  { code: "MZ", name: "Mozambique", flag: "🇲🇿" },
  { code: "ZM", name: "Zambia", flag: "🇿🇲" },
  { code: "ZW", name: "Zimbabwe", flag: "🇿🇼" },
  { code: "NA", name: "Namibia", flag: "🇳🇦" },
  { code: "BW", name: "Botswana", flag: "🇧🇼" },
  { code: "MU", name: "Mauritius", flag: "🇲🇺" },
  { code: "RW", name: "Rwanda", flag: "🇷🇼" },
  { code: "SD", name: "Sudan", flag: "🇸🇩" },
  { code: "SS", name: "South Sudan", flag: "🇸🇸" },
  { code: "ML", name: "Mali", flag: "🇲🇱" },
  { code: "BF", name: "Burkina Faso", flag: "🇧🇫" },
  { code: "NE", name: "Niger", flag: "🇳🇪" },
  { code: "GN", name: "Guinea", flag: "🇬🇳" },
  { code: "LR", name: "Liberia", flag: "🇱🇷" },
  { code: "SL", name: "Sierra Leone", flag: "🇸🇱" },
  { code: "BJ", name: "Benin", flag: "🇧🇯" },
  { code: "TG", name: "Togo", flag: "🇹🇬" },
  { code: "GA", name: "Gabon", flag: "🇬🇦" },
  { code: "CG", name: "Congo", flag: "🇨🇬" },
  { code: "CD", name: "DR Congo", flag: "🇨🇩" },
  { code: "GQ", name: "Equatorial Guinea", flag: "🇬🇶" },
  { code: "ST", name: "Sao Tome and Principe", flag: "🇸🇹" },
  { code: "SC", name: "Seychelles", flag: "🇸🇨" },
  { code: "MG", name: "Madagascar", flag: "🇲🇬" },
  { code: "MR", name: "Mauritania", flag: "🇲🇷" },
  { code: "ER", name: "Eritrea", flag: "🇪🇷" },
  { code: "DJ", name: "Djibouti", flag: "🇩🇯" },
  { code: "SO", name: "Somalia", flag: "🇸🇴" },
  { code: "LS", name: "Lesotho", flag: "🇱🇸" },
  { code: "SZ", name: "Eswatini", flag: "🇸🇿" },
  { code: "MW", name: "Malawi", flag: "🇲🇼" },
  { code: "BI", name: "Burundi", flag: "🇧🇮" },
  { code: "KM", name: "Comoros", flag: "🇰🇲" },
] as const;

export const middlewareConstants = {
  COOKIE_NAME: "affiliatebase_admin_token",
  LOGIN_PATH: "/admin/login",
  PROTECTED_PATHS: ["/admin", "/api/admin"],
  PUBLIC_PATHS: ["/admin/login", "/api/auth/login"],
};
