import { Category } from "./types";

export const SESSION_STORAGE_KEYS = {
  SESSION_ID: "ta_session_id",
  VIEWED_PREFIX: "ta_viewed_",
} as const;

export const CATEGORIES = [
  "Artificial Intelligence",
  "SaaS",
  "Developer Tools",
  "Fintech",
  "Productivity",
  "Marketing",
  "E-commerce",
  "Design Tools",
  "No-Code",
  "Analytics",
  "Education",
  "Health & Fitness",
  "Social Media",
  "Content Creation",
  "Sales",
  "Customer Support",
  "Recruiting & HR",
  "Real Estate",
  "Travel",
  "Security",
] as const;

export const CATEGORY_ICONS: Readonly<Record<Category, string>> = {
  "Artificial Intelligence": "HiSparkles",
  SaaS: "HiCloud",
  "Developer Tools": "HiWrenchScrewdriver",
  Fintech: "HiCreditCard",
  Productivity: "HiBolt",
  Marketing: "HiMegaphone",
  "E-commerce": "HiShoppingCart",
  "Design Tools": "HiPaintBrush",
  "No-Code": "HiPuzzlePiece",
  Analytics: "HiChartBar",
  Education: "HiAcademicCap",
  "Health & Fitness": "HiHeart",
  "Social Media": "HiDevicePhoneMobile",
  "Content Creation": "HiPencilSquare",
  Sales: "HiBanknotes",
  "Customer Support": "HiChatBubbleLeftRight",
  "Recruiting & HR": "HiUserGroup",
  "Real Estate": "HiHomeModern",
  Travel: "HiPaperAirplane",
  Security: "HiLockClosed",
} as const;

export const VALID_COUNTRIES = [
  "US",
  "GB",
  "DE",
  "FR",
  "ES",
  "IT",
  "NL",
  "BE",
  "AT",
  "CH",
  "SE",
  "NO",
  "DK",
  "FI",
  "PL",
  "CZ",
  "PT",
  "IE",
  "RU",
  "UA",
  "CA",
  "MX",
  "BR",
  "AR",
  "CO",
  "CL",
  "AU",
  "NZ",
  "JP",
  "KR",
  "CN",
  "HK",
  "SG",
  "IN",
  "ID",
  "TH",
  "VN",
  "MY",
  "PH",
  "AE",
  "SA",
  "IL",
  "TR",
  "EG",
  "ZA",
  "NG",
  "KE",
  "Other",
] as const;

export const COUNTRIES = [
  { code: "US", name: "United States", flag: "🇺🇸" },
  { code: "GB", name: "United Kingdom", flag: "🇬🇧" },
  { code: "DE", name: "Germany", flag: "🇩🇪" },
  { code: "FR", name: "France", flag: "🇫🇷" },
  { code: "ES", name: "Spain", flag: "🇪🇸" },
  { code: "IT", name: "Italy", flag: "🇮🇹" },
  { code: "NL", name: "Netherlands", flag: "🇳🇱" },
  { code: "BE", name: "Belgium", flag: "🇧🇪" },
  { code: "AT", name: "Austria", flag: "🇦🇹" },
  { code: "CH", name: "Switzerland", flag: "🇨🇭" },
  { code: "SE", name: "Sweden", flag: "🇸🇪" },
  { code: "NO", name: "Norway", flag: "🇳🇴" },
  { code: "DK", name: "Denmark", flag: "🇩🇰" },
  { code: "FI", name: "Finland", flag: "🇫🇮" },
  { code: "PL", name: "Poland", flag: "🇵🇱" },
  { code: "CZ", name: "Czech Republic", flag: "🇨🇿" },
  { code: "PT", name: "Portugal", flag: "🇵🇹" },
  { code: "IE", name: "Ireland", flag: "🇮🇪" },
  { code: "RU", name: "Russia", flag: "🇷🇺" },
  { code: "UA", name: "Ukraine", flag: "🇺🇦" },
  { code: "CA", name: "Canada", flag: "🇨🇦" },
  { code: "MX", name: "Mexico", flag: "🇲🇽" },
  { code: "BR", name: "Brazil", flag: "🇧🇷" },
  { code: "AR", name: "Argentina", flag: "🇦🇷" },
  { code: "CO", name: "Colombia", flag: "🇨🇴" },
  { code: "CL", name: "Chile", flag: "🇨🇱" },
  { code: "AU", name: "Australia", flag: "🇦🇺" },
  { code: "NZ", name: "New Zealand", flag: "🇳🇿" },
  { code: "JP", name: "Japan", flag: "🇯🇵" },
  { code: "KR", name: "South Korea", flag: "🇰🇷" },
  { code: "CN", name: "China", flag: "🇨🇳" },
  { code: "HK", name: "Hong Kong", flag: "🇭🇰" },
  { code: "SG", name: "Singapore", flag: "🇸🇬" },
  { code: "IN", name: "India", flag: "🇮🇳" },
  { code: "ID", name: "Indonesia", flag: "🇮🇩" },
  { code: "TH", name: "Thailand", flag: "🇹🇭" },
  { code: "VN", name: "Vietnam", flag: "🇻🇳" },
  { code: "MY", name: "Malaysia", flag: "🇲🇾" },
  { code: "PH", name: "Philippines", flag: "🇵🇭" },
  { code: "AE", name: "United Arab Emirates", flag: "🇦🇪" },
  { code: "SA", name: "Saudi Arabia", flag: "🇸🇦" },
  { code: "IL", name: "Israel", flag: "🇮🇱" },
  { code: "TR", name: "Turkey", flag: "🇹🇷" },
  { code: "EG", name: "Egypt", flag: "🇪🇬" },
  { code: "ZA", name: "South Africa", flag: "🇿🇦" },
  { code: "NG", name: "Nigeria", flag: "🇳🇬" },
  { code: "KE", name: "Kenya", flag: "🇰🇪" },
] as const;

export const middlewareConstants = {
  COOKIE_NAME: "affiliatebase_admin_token",
  LOGIN_PATH: "/admin/login",
  PROTECTED_PATHS: ["/admin", "/api/admin"],
  PUBLIC_PATHS: ["/admin/login", "/api/auth/login"],
};
