import { Category } from "./types";

export const SESSION_STORAGE_KEYS = {
  SESSION_ID: "ta_session_id",
  VIEWED_PREFIX: "ta_viewed_",
} as const;

export const CATEGORIES = [
  "Artificial Intelligence",
  "Marketing",
  "E-commerce",
  "Design Tools",
  "Developer Tools",
  "Fintech",
  "Productivity",
  "No-Code",
  "Analytics",
  "SaaS",
  "Hosting & Web",
  "Utilities",
  "Education",
] as const;

export const CATEGORY_ICONS: Readonly<Record<Category, string>> = {
  "Artificial Intelligence": "HiSparkles",
  Marketing: "HiMegaphone",
  "E-commerce": "HiShoppingCart",
  "Design Tools": "HiPaintBrush",
  "Developer Tools": "HiWrenchScrewdriver",
  Fintech: "HiCreditCard",
  Productivity: "HiBolt",
  "No-Code": "HiPuzzlePiece",
  Analytics: "HiChartBar",
  SaaS: "HiCloud",
  "Hosting & Web": "HiServerStack",
  Utilities: "HiWrench",
  Education: "HiAcademicCap",
} as const;

export const CATEGORY_SLUGS: Readonly<Record<Category, string>> = {
  "Artificial Intelligence": "ai",
  Marketing: "marketing",
  "E-commerce": "ecommerce",
  "Design Tools": "design-tools",
  "Developer Tools": "developer-tools",
  Fintech: "fintech",
  Productivity: "productivity",
  "No-Code": "no-code",
  Analytics: "analytics",
  SaaS: "saas",
  "Hosting & Web": "hosting-web",
  Utilities: "utilities",
  Education: "education",
} as const;

export const getSlugFromCategory = (category: Category): string =>
  CATEGORY_SLUGS[category] || category.toLowerCase().replace(/\s+/g, "-");

export const getCategoryFromSlug = (slug: string): Category | null => {
  const entry = Object.entries(CATEGORY_SLUGS).find(([_, s]) => s === slug);
  return entry ? (entry[0] as Category) : null;
};

export const VALID_COUNTRIES = [
  "US",
  "GB",
  "DE",
  "FR",
  "ES",
  "IT",
  "NL",
  "BE",
  "AT",
  "CH",
  "SE",
  "NO",
  "DK",
  "FI",
  "PL",
  "CZ",
  "PT",
  "IE",
  "RU",
  "UA",
  "CA",
  "MX",
  "BR",
  "AR",
  "CO",
  "CL",
  "AU",
  "NZ",
  "JP",
  "KR",
  "CN",
  "HK",
  "SG",
  "IN",
  "ID",
  "TH",
  "VN",
  "MY",
  "PH",
  "AE",
  "SA",
  "IL",
  "TR",
  "EG",
  "ZA",
  "NG",
  "KE",
  "RO",
  "GR",
  "HU",
  "BG",
  "HR",
  "SK",
  "LT",
  "LV",
  "EE",
  "SI",
  "LU",
  "IS",
  "PK",
  "TW",
  "KZ",
  "LK",
  "BD",
  "PE",
  "UY",
  "EC",
  "CR",
  "PA",
  "MA",
  "GH",
  "ET",
  "TZ",
  "KW",
  "QA",
  "BH",
  "OM",
  "Other",
] as const;

export const COUNTRIES = [
  { code: "US", name: "United States", flag: "🇺🇸" },
  { code: "GB", name: "United Kingdom", flag: "🇬🇧" },
  { code: "DE", name: "Germany", flag: "🇩🇪" },
  { code: "FR", name: "France", flag: "🇫🇷" },
  { code: "ES", name: "Spain", flag: "🇪🇸" },
  { code: "IT", name: "Italy", flag: "🇮🇹" },
  { code: "NL", name: "Netherlands", flag: "🇳🇱" },
  { code: "BE", name: "Belgium", flag: "🇧🇪" },
  { code: "AT", name: "Austria", flag: "🇦🇹" },
  { code: "CH", name: "Switzerland", flag: "🇨🇭" },
  { code: "SE", name: "Sweden", flag: "🇸🇪" },
  { code: "NO", name: "Norway", flag: "🇳🇴" },
  { code: "DK", name: "Denmark", flag: "🇩🇰" },
  { code: "FI", name: "Finland", flag: "🇫🇮" },
  { code: "PL", name: "Poland", flag: "🇵🇱" },
  { code: "CZ", name: "Czech Republic", flag: "🇨🇿" },
  { code: "PT", name: "Portugal", flag: "🇵🇹" },
  { code: "IE", name: "Ireland", flag: "🇮🇪" },
  { code: "RU", name: "Russia", flag: "🇷🇺" },
  { code: "UA", name: "Ukraine", flag: "🇺🇦" },
  { code: "CA", name: "Canada", flag: "🇨🇦" },
  { code: "MX", name: "Mexico", flag: "🇲🇽" },
  { code: "BR", name: "Brazil", flag: "🇧🇷" },
  { code: "AR", name: "Argentina", flag: "🇦🇷" },
  { code: "CO", name: "Colombia", flag: "🇨🇴" },
  { code: "CL", name: "Chile", flag: "🇨🇱" },
  { code: "AU", name: "Australia", flag: "🇦🇺" },
  { code: "NZ", name: "New Zealand", flag: "🇳🇿" },
  { code: "JP", name: "Japan", flag: "🇯🇵" },
  { code: "KR", name: "South Korea", flag: "🇰🇷" },
  { code: "CN", name: "China", flag: "🇨🇳" },
  { code: "HK", name: "Hong Kong", flag: "🇭🇰" },
  { code: "SG", name: "Singapore", flag: "🇸🇬" },
  { code: "IN", name: "India", flag: "🇮🇳" },
  { code: "ID", name: "Indonesia", flag: "🇮🇩" },
  { code: "TH", name: "Thailand", flag: "🇹🇭" },
  { code: "VN", name: "Vietnam", flag: "🇻🇳" },
  { code: "MY", name: "Malaysia", flag: "🇲🇾" },
  { code: "PH", name: "Philippines", flag: "🇵🇭" },
  { code: "AE", name: "United Arab Emirates", flag: "🇦🇪" },
  { code: "SA", name: "Saudi Arabia", flag: "🇸🇦" },
  { code: "IL", name: "Israel", flag: "🇮🇱" },
  { code: "TR", name: "Turkey", flag: "🇹🇷" },
  { code: "EG", name: "Egypt", flag: "🇪🇬" },
  { code: "ZA", name: "South Africa", flag: "🇿🇦" },
  { code: "NG", name: "Nigeria", flag: "🇳🇬" },
  { code: "KE", name: "Kenya", flag: "🇰🇪" },
  { code: "RO", name: "Romania", flag: "🇷🇴" },
  { code: "GR", name: "Greece", flag: "🇬🇷" },
  { code: "HU", name: "Hungary", flag: "🇭🇺" },
  { code: "BG", name: "Bulgaria", flag: "🇧🇬" },
  { code: "HR", name: "Croatia", flag: "🇭🇷" },
  { code: "SK", name: "Slovakia", flag: "🇸🇰" },
  { code: "LT", name: "Lithuania", flag: "🇱🇹" },
  { code: "LV", name: "Latvia", flag: "🇱🇻" },
  { code: "EE", name: "Estonia", flag: "🇪🇪" },
  { code: "SI", name: "Slovenia", flag: "🇸🇮" },
  { code: "LU", name: "Luxembourg", flag: "🇱🇺" },
  { code: "IS", name: "Iceland", flag: "🇮🇸" },
  { code: "PK", name: "Pakistan", flag: "🇵🇰" },
  { code: "TW", name: "Taiwan", flag: "🇹🇼" },
  { code: "KZ", name: "Kazakhstan", flag: "🇰🇿" },
  { code: "LK", name: "Sri Lanka", flag: "🇱🇰" },
  { code: "BD", name: "Bangladesh", flag: "🇧🇩" },
  { code: "PE", name: "Peru", flag: "🇵🇪" },
  { code: "UY", name: "Uruguay", flag: "🇺🇾" },
  { code: "EC", name: "Ecuador", flag: "🇪🇨" },
  { code: "CR", name: "Costa Rica", flag: "🇨🇷" },
  { code: "PA", name: "Panama", flag: "🇵🇦" },
  { code: "MA", name: "Morocco", flag: "🇲🇦" },
  { code: "GH", name: "Ghana", flag: "🇬🇭" },
  { code: "ET", name: "Ethiopia", flag: "🇪🇹" },
  { code: "TZ", name: "Tanzania", flag: "🇹🇿" },
  { code: "KW", name: "Kuwait", flag: "🇰🇼" },
  { code: "QA", name: "Qatar", flag: "🇶🇦" },
  { code: "BH", name: "Bahrain", flag: "🇧🇭" },
  { code: "OM", name: "Oman", flag: "🇴🇲" },
] as const;

export const middlewareConstants = {
  COOKIE_NAME: "affiliatebase_admin_token",
  LOGIN_PATH: "/admin/login",
  PROTECTED_PATHS: ["/admin", "/api/admin"],
  PUBLIC_PATHS: ["/admin/login", "/api/auth/login"],
};
